# Generated by Django 3.2.12 on 2024-03-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='这是文章标题', max_length=64, verbose_name='文章标题')),
                ('desc', models.CharField(help_text='这是文章简介', max_length=255, verbose_name='文章简介')),
                ('content', models.TextField(help_text='这是文章内容', verbose_name='文章内容')),
                ('create_time', models.DateField(auto_now_add=True, help_text='这是创建时间', verbose_name='创建时间')),
                ('up_num', models.BigIntegerField(default=0, help_text='这是点赞数', verbose_name='点赞数')),
                ('up_down', models.BigIntegerField(default=0, help_text='这是点踩数', verbose_name='点踩数')),
                ('comment_num', models.BigIntegerField(default=0, help_text='这是评论数', verbose_name='评论数')),
            ],
        ),
        migrations.CreateModel(
            name='Article2Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='这是文章分类', max_length=32, verbose_name='文章分类')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='这是评论内容', max_length=255, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, help_text='这是评论时间', verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='这是文章标签', max_length=32, verbose_name='文章标签')),
            ],
        ),
        migrations.CreateModel(
            name='UpAndDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(help_text='这是是否点赞', verbose_name='是否点赞')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
