# Generated by Django 3.2.12 on 2024-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='这是站点名称', max_length=32, verbose_name='站点名称')),
                ('site_title', models.CharField(help_text='这是站点标题', max_length=32, verbose_name='站点标题')),
                ('site_theme', models.CharField(help_text='这是站点样式', max_length=64, verbose_name='站点样式')),
            ],
        ),
    ]
