# Generated by Django 3.2.12 on 2024-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='这是广告标题', max_length=64, verbose_name='广告标题')),
                ('content', models.TextField(help_text='这是广告内容', verbose_name='广告内容')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='这是创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='这是更新时间', verbose_name='更新时间')),
                ('mobile', models.CharField(blank=True, default='', help_text='这是手机号', max_length=11, verbose_name='手机号')),
                ('img', models.ImageField(default='', help_text='这是广告图片', upload_to='advImg/', verbose_name='广告图片')),
                ('is_background_img', models.BooleanField(default=False, help_text='这是是否为背景图', verbose_name='是否为背景图')),
            ],
        ),
    ]
