# Generated by Django 3.2.12 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_adv_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='img',
            field=models.FileField(default='advImg/kaixin.png', help_text='这是广告图片', upload_to='advImg/', verbose_name='广告图片'),
        ),
    ]
